# Boilerplate code generated by OVITO Pro 3.7.2
from ovito.io import *
from ovito.modifiers import *
from ovito.data import *
from ovito.pipeline import *
from ovito.vis import *
from ovito.qt_compat import QtCore

# Data import:
pipeline = import_file('/data/emrosky-sim/Freezing_Simulations/Cavity_Within_Volume/Ibeam_capillary/Ten_Molecular_Layers/Wide_Ibeam/Constant_Cooling_240K/run_13/prod.ibeam_cooling_13.dump', multiple_frames = True)

# Visual element initialization:
data = pipeline.compute() # Evaluate new pipeline to gain access to visual elements associated with the imported data objects.
data.particles.vis.radius = 0.6
del data # Done accessing input DataCollection of pipeline.
pipeline.add_to_scene()

# Chill+:
mod = ChillPlusModifier()
mod.structures[ChillPlusModifier.Type.OTHER].enabled = False
mod.structures[ChillPlusModifier.Type.HYDRATE].enabled = False
mod.structures[ChillPlusModifier.Type.INTERFACIAL_HYDRATE].enabled = False
pipeline.modifiers.append(mod)

# Select type:
pipeline.modifiers.append(SelectTypeModifier(
    property = 'Structure Type', 
    types = {0, 3, 4, 5}))

# Delete selected:
pipeline.modifiers.append(DeleteSelectedModifier())

# Construct surface mesh:
mod = ConstructSurfaceModifier()
mod.radius = 5.8
mod.smoothing_level = 7
mod.vis.show_cap = False
mod.enabled = False
pipeline.modifiers.append(mod)

# Viewport setup:
vp = Viewport(
    type = Viewport.Type.Front, 
    fov = 55.1146107784, 
    camera_dir = (-0.0, 1.0, -0.0), 
    camera_pos = (78.752, 18.225268370000002, 20.269765242270665))

# Rendering:
vp.render_anim(filename='/data/emrosky-sim/Freezing_Simulations/Cavity_Within_Volume/Ibeam_capillary/Ten_Molecular_Layers/Wide_Ibeam/run_10.avi', size=(1000, 1000), fps=20, range=(5640, 6602))